spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0:///hhplus
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 5000
      validation-timeout: 3000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        connection:
          isolation: 2
        jdbc:
          batch_size: 0

  flyway:
    enabled: false

logging:
  level:
    kr.hhplus.be.server: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG